CREAR TABLAS
CREATE DATABASE UNIVERSIDAD_LOS_SABIOS;
USE UNIVERSIDAD_LOS_SABIOS;



CREATE TABLE PERSONA(
	ID_PERSONA INT AUTO_INCREMENT PRIMARY KEY,
	TIPO_DOCUMENTO ENUM ('C.C','C.E','P.A','T.I'),
	DOCUMENTO VARCHAR(10),
	NOMBRE1 VARCHAR (20),
	NOMBRE2 VARCHAR (20),
	APELLIDO1 VARCHAR (20),
	APELLIDO2 VARCHAR (20),
	TELEFONO VARCHAR (12),
	FECHA_NACIMIENTO DATE,
	GENERO ENUM ('M','F'),
	ID_DIRECCION INT,
	ID_CIUDAD INT,
	TIPO_PERSONA ENUM ('DOCENTE','ESTUDIANTE')
);

CREATE TABLE DOCENTE(
	ID_PERSONA INT,
	ID_DEPARTAMENTO INT);

CREATE TABLE DEPARTAMENTO(
	ID_DEPARTAMENTO INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR (50)
	);

CREATE TABLE CIUDAD(
	ID_CIUDAD INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR (20)
);

CREATE TABLE DIRECCION(
	ID_DIRECCION INT AUTO_INCREMENT PRIMARY KEY,
	PRINCIPAL ENUM ('CALLE','CARRERA','AVENIDA'),
	NUMERO VARCHAR (7),
	TIPO ENUM ('CASA','APARTAMENTO')
);

CREATE TABLE ASIGNATURA(
	ID_ASIGNATURA INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR (50),
	CREDITOS INT,
	ID_DOCENTE INT,
	ID_PROGRAMA INT,
	ID_CURSO INT,
	ID_PERIODO INT );

CREATE TABLE HORARIO(
	ID_HORARIO INT AUTO_INCREMENT PRIMARY KEY,
	DIA ENUM ('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES'),
	INICIO TIME,
	FINAL TIME,
	ID_SALON INT,
	ID_ASIGNATURA INT );

CREATE TABLE SALON(
	ID_SALON INT AUTO_INCREMENT PRIMARY KEY,
	CUPO INT,
	ID_EDIFICIO INT,
	ID_PISO INT,
SERIAL_SALON VARCHAR(5)
);


CREATE TABLE EDIFICIO(
	ID_EDIFICIO INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50)
);


CREATE TABLE CURSO(
	ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(40),
	GUIA_CATEDRA VARCHAR (250),
	CODIGO VARCHAR (10)
);


CREATE TABLE PROGRAMA(
	ID_PROGRAMA INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR (30),
	NIVEL VARCHAR (15),
	CODIGO VARCHAR (10)
);


CREATE TABLE PERIODO(
	ID_PERIODO INT AUTO_INCREMENT PRIMARY KEY,
	CODIGO VARCHAR (10)
);


CREATE TABLE MATRICULA(
	ID_MATRICULA INT AUTO_INCREMENT PRIMARY KEY,
	ID_ESTUDIANTE INT,
	ID_ASIGNATURA INT,
	ID_PERIODO INT);


CREATE TABLE TARIFAS(
	ID_TARIFAS INT AUTO_INCREMENT PRIMARY KEY,
	ID_PERIODO INT,
	ID_PROGRAMA INT,
	VALOR INT);
	
CREACIÓN DE LLAVES FORÁNEAS:


ALTER TABLE PERSONA ADD CONSTRAINT FK_PERSONA_CIUDAD  FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD (ID_CIUDAD);

ALTER TABLE PERSONA ADD CONSTRAINT FK_PERSONA_DIRECCION FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION (ID_DIRECCION);


ALTER TABLE DOCENTE ADD CONSTRAINT FK_DOCENTE_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA);

ALTER TABLE DOCENTE ADD CONSTRAINT FK_DOCENTE_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO);

ALTER TABLE ASIGNATURA ADD CONSTRAINT FK_ASIGNATURA_PERSONA FOREIGN KEY (ID_DOCENTE) REFERENCES PERSONA (ID_PERSONA);

ALTER TABLE ASIGNATURA ADD CONSTRAINT FK_ASIGNATURA_PROGRAMA FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA (ID_PROGRAMA);

ALTER TABLE ASIGNATURA ADD CONSTRAINT FK_ASIGNATURA_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO);

ALTER TABLE ASIGNATURA ADD CONSTRAINT FK_ASIGNATURA_PERIODO FOREIGN KEY (ID_PERIODO) REFERENCES PERIODO (ID_PERIODO);

ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_PERSONA FOREIGN KEY (ID_ESTUDIANTE) REFERENCES PERSONA (ID_PERSONA);

ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_ASIGNATURA FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA (ID_ASIGNATURA);

ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_PERIODO FOREIGN KEY (ID_PERIODO) REFERENCES PERIODO (ID_PERIODO);

ALTER TABLE HORARIO ADD CONSTRAINT FK_HORARIO_ASIGNATURA FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA (ID_ASIGNATURA);

ALTER TABLE HORARIO ADD CONSTRAINT FK_HORARIO_SALON FOREIGN KEY (ID_SALON) REFERENCES SALON (ID_SALON);

ALTER TABLE SALON ADD CONSTRAINT FK_SALON_EDIFICIO FOREIGN KEY (ID_EDIFICIO) REFERENCES EDIFICIO (ID_EDIFICIO);

ALTER TABLE TARIFAS ADD CONSTRAINT FK_TARIFAS_PROGRAMA FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA (ID_PROGRAMA);

ALTER TABLE TARIFAS ADD CONSTRAINT FK_TARIFAS_PERIODO FOREIGN KEY (ID_PERIODO) REFERENCES PERIODO (ID_PERIODO);

